### ISSUE TITLE
bash script in README.md needs fix

### ISSUE THREAD

**Issue by sinzin91** [derekwyatt/vim-scala#145] opened 2017-09-25 18:00 UTC
There needs to be a space before the final semi-colon for it to work:

```
mkdir -p ~/.vim/{ftdetect,indent,syntax} && for d in ftdetect indent syntax ; do curl -o ~/.vim/$d/scala.vim https://raw.githubusercontent.com/derekwyatt/vim-scala/master/$d/scala.vim\ ; done
```

**Comment by giftig** [comment] 2017-12-16 12:46
Which shell are you using? That's not how bash works.

**Comment by Dmitry-Erokhin** [comment] 2017-12-29 07:35
I think it was zsh. Faced same issue. This shell "helps" you by escaping semicolon on paste and `...la.vim; done` becomes `...la.vim\; done`. So if you'll add extra space it will not alter original: `...la.vim ; done`

**Comment by giftig** [comment] 2017-12-31 12:53
I've used zsh before and I recall it doing that for urls to make sure you don't break the urlencoding, so I suspect that's why it's escaped the semicolon. The proper way to fix that would be to single-quote the url instead (which should be done usually anyway, as plenty of common url characters will be interpreted as glob characters and break it even in bash, and it's just fortunate this url doesn't contain any)

**Comment by giftig** [comment] 2017-12-31 12:58
Actually I just tried with a zsh docker container and can't reproduce the problem. Is that escaping not a feature of the terminal emulator, rather than your shell? I can't imagine how the shell would even do it itself, it hasn't received input by that point. Which terminal emulator are you using? I seem to recall behaviour similar to what you describe with iterm2 on mac OSX.

**Comment by derekwyatt** [comment] 2017-12-31 14:09
Zsh has lots of interesting options that get more complicated if you're
using oh-my-zsh. I suspect you've got something interesting set there. At
any rate this isn't a real issue so I'll be closing it.

**Closed** 2017-12-31 14:10 UTC
